defmodule RC.ShareToken do
  @moduledoc """
  Unguessable share tokens for Forge maps/scenarios and game lobbies.

  Numeric ids in URLs are enumerable, so every link the app hands out
  (share buttons, list rows, the address bar, Discord posts) carries the
  row's `share_token` instead. A token URL is a capability: whoever has
  it may view the row even when it's a draft or a private lobby, because
  the person sharing it clearly meant them to. Numeric URLs keep working
  for what is public anyway (published designs, listed lobbies) and for
  the people who could already see the row.

  12 random bytes, base64url without padding: 16 characters, 96 bits.
  Generated by Ecto `autogenerate` on insert, so every insert path gets
  one; the add_share_tokens migration backfilled existing rows.
  """

  @bytes 12
  @pattern ~r/\A[A-Za-z0-9_-]{16}\z/

  def generate, do: @bytes |> :crypto.strong_rand_bytes() |> Base.url_encode64(padding: false)

  @doc """
  Classifies a URL segment: `{:id, integer}` for a plain numeric id,
  `{:token, token}` for something shaped like a share token, `:error`
  otherwise (so garbage never reaches a query).
  """
  def parse_ref(ref) when is_integer(ref), do: {:id, ref}

  def parse_ref(ref) when is_binary(ref) do
    case Integer.parse(ref) do
      {id, ""} ->
        {:id, id}

      _ ->
        if Regex.match?(@pattern, ref), do: {:token, ref}, else: :error
    end
  end

  def parse_ref(_), do: :error
end
